### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by GuiDevloper** [GuiDevloper/i18n-typings#1]
- [x] Add automatizated tests (Hello Jest, my old friend) 780f59d3ad0b9ce1c24cdae55ed8a5b8ad5d8b14
- [x] Build into an CLI tool 870a45e967cc33800c8e1fec850f05ff037e10f8
- [ ] Integrate with TS compilation? (understanding `tsconfig` info)
- ~~Generate keys from structure without manual typing (e.g `type Page = { title: string }` -> `Page.title`)~~
